import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import "./globals.css";


export const metadata = {
  title: "Empress App",
  description: "Generated by create next app",
  icons: "/empress_logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> 
        
        {children}
        <Footer />
        
      </body>
    </html>
  );
}
