import EmpressChatbot from "@/components/chatbot/empress-chatbot";
import "./globals.css";
import QueryProvider from "./query-provider";

export const metadata = {
  title: "Empress App",
  description: "Generated by create next app",
  icons: "/empress_logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
      <EmpressChatbot />
    </html>
  );
}
